"""The CLI driver — the decomposition core's first (and currently only) frontend.

Docs: https://cj-mills.github.io/cjm-transcript-decomp-corecli.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/cli.ipynb.

# %% auto #0
__all__ = ['logger', 'build_parser', 'load_capabilities', 'run_command', 'main']

# %% ../nbs/cli.ipynb #62cfebb1
import argparse
import asyncio
import logging
from pathlib import Path
from typing import Any, Dict, List, Optional

from cjm_plugin_system.core.manager import PluginManager
from cjm_plugin_system.core.queue import JobQueue

from .models import DecompConfig
from .pipeline import run_decomp, load_source_manifest

logger = logging.getLogger(__name__)

# %% ../nbs/cli.ipynb #3d7c5681
def build_parser() -> argparse.ArgumentParser:  # Configured CLI parser
    """Build the CLI parser (subcommands: run)."""
    parser = argparse.ArgumentParser(
        prog="cjm-transcript-decomp-core",
        description="Headless transcript decomposition: VAD + forced alignment -> fine-spine graph extension.",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    run = sub.add_parser("run", help="Extend a transcription-emitted graph root with the fine spine")
    run.add_argument("manifest", help="Transcription-core run manifest JSON (the source to decompose)")
    run.add_argument("--manifests-dir", default=".cjm/manifests", help="Capability manifests directory")
    run.add_argument("--vad-plugin", default="cjm-media-plugin-silero-vad", help="VAD capability name")
    run.add_argument("--fa-plugin", default="cjm-transcription-plugin-qwen3-forced-aligner", help="Forced-alignment capability name")
    run.add_argument("--graph-plugin", default="cjm-graph-plugin-sqlite", help="Graph-storage capability name")
    run.add_argument("--graph-db-path", default=None,
                     help="Explicit graph DB path override (F10; scratch-graph loop-backs; default: the capability's configured db_path)")
    run.add_argument("--text-from", default=None,
                     help="Authoritative transcriber for layer-0 text (the ACCURACY model; "
                          "required when the manifest carries multiple transcribers; "
                          "default: the manifest's sole transcriber)")
    run.add_argument("--sysmon-plugin", default=None, help="MonitorPlugin capability for GPU subtree attribution (CR-7); loaded first; default: no monitor")
    run.add_argument("--language", default="English", help="Forced-alignment language")
    run.add_argument("--force", action="store_true", help="Bypass capability-side caches (VAD + FA)")
    run.add_argument("-y", "--yes", action="store_true", help="Auto-accept HITL seams (headless mode)")
    run.add_argument("--output", default=None, help="Decomp-manifest output path (default: runs/<run_id>.json)")
    run.add_argument("-v", "--verbose", action="store_true", help="DEBUG-level logging")
    return parser

# %% ../nbs/cli.ipynb #607602e9
def load_capabilities(
    manager: PluginManager,   # Freshly constructed manager
    instance_ids: List[str],  # Capability names to load (default instances), in order
    configs: Optional[Dict[str, Dict[str, Any]]] = None,  # Per-capability config overrides (caller-wins, C8)
) -> None:
    """Discover manifests + load each requested capability (default instance)."""
    manager.discover_manifests()
    discovered = {m.name: m for m in manager.discovered}
    for iid in instance_ids:
        meta = discovered.get(iid)
        if meta is None:
            raise SystemExit(
                f"capability {iid!r} not found in manifests "
                f"(discovered: {sorted(discovered)}) — run cjm-ctl install-all first"
            )
        if not manager.load_plugin(meta, config=(configs or {}).get(iid)):
            raise SystemExit(f"failed to load capability {iid!r}")
        logger.info(f"loaded {iid}")

# %% ../nbs/cli.ipynb #c6fda10a
async def run_command(
    args: argparse.Namespace,  # Parsed CLI arguments for the `run` subcommand
) -> int:  # Process exit code (0 = all sources extended + verified)
    """Execute the `run` subcommand: extend a transcription-emitted root with the fine spine."""
    manifest_path = str(Path(args.manifest).resolve())
    if not Path(manifest_path).exists():
        raise SystemExit(f"source manifest not found: {manifest_path}")

    cfg = DecompConfig(
        vad_plugin=args.vad_plugin,
        fa_plugin=args.fa_plugin,
        graph_plugin=args.graph_plugin,
        text_from=args.text_from,
        language=args.language,
        force=args.force,
        assume_yes=args.yes,
    )

    # CR-7 GPU subtree attribution is opt-in: --sysmon-plugin threads the monitor
    # name into BOTH the manager and the queue; the monitor loads FIRST so GPU
    # capabilities' samples record gpu_memory_mb_peak (voxtral-vllm e2e pattern).
    manager = PluginManager(
        search_paths=[Path(args.manifests_dir)],
        sysmon_plugin_name=args.sysmon_plugin,
    )
    instance_ids = [cfg.vad_plugin, cfg.fa_plugin, cfg.graph_plugin]
    load_order = ([args.sysmon_plugin] if args.sysmon_plugin else []) + instance_ids
    # F10: --graph-db-path threads a caller-wins config into the graph load
    # (the C8 pattern correction-core already used; scratch-graph loop-backs).
    configs = ({cfg.graph_plugin: {"db_path": args.graph_db_path}}
               if args.graph_db_path else None)
    load_capabilities(manager, load_order, configs=configs)

    queue = JobQueue(deps=manager, sysmon_plugin_name=args.sysmon_plugin)
    await queue.start()
    try:
        manifest = await run_decomp(manager, queue, cfg, manifest_path)
    finally:
        await queue.stop()
        for iid in reversed(load_order):  # Reverse load order; the monitor unloads last
            try:
                manager.unload_plugin(iid)
            except Exception as e:  # Best-effort teardown; never mask the run's outcome
                logger.warning(f"unload {iid} failed: {e}")

    out = Path(args.output) if args.output else Path("runs") / f"{manifest.run_id}.json"
    manifest.save(out)
    n_manifest_sources = len(load_source_manifest(manifest_path).get("sources", []) or [])
    n_sources = len(manifest.sources)
    n_segs = sum(s.segment_count for s in manifest.sources)
    print(f"decomp manifest: {out}")
    print(f"sources extended: {n_sources}/{n_manifest_sources}  segment nodes: {n_segs}")
    return 0 if n_sources == n_manifest_sources else 1

# %% ../nbs/cli.ipynb #fe7332f2
def main(
    argv: Optional[List[str]] = None,  # Argument list override (None = sys.argv)
) -> int:  # Process exit code
    """CLI entry point (console script: `cjm-transcript-decomp-core`)."""
    args = build_parser().parse_args(argv)
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s :: %(message)s",
    )
    if args.command == "run":
        return asyncio.run(run_command(args))
    raise SystemExit(f"unknown command: {args.command}")
