"""Graph-spine construction, commit, and skeptical-lens verification. Builds Document +
Segment nodes and STARTS_WITH / NEXT / PART_OF edges (pure), commits them through the
graph-storage capability via the job queue, and re-queries the graph to verify.

Docs: https://cj-mills.github.io/cjm-transcript-decomp-coregraph.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/graph.ipynb.

# %% auto #0
__all__ = ['build_source_ref', 'build_graph_payload', 'commit_graph', 'VerificationResult', 'verify_document']

# %% ../nbs/graph.ipynb #116a0af1
from uuid import uuid4
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

from cjm_plugin_system.core.queue import JobQueue, JobStatus
from cjm_context_graph_primitives.locators import FileRef
from cjm_context_graph_primitives.provenance import SourceRef
from cjm_context_graph_primitives.graph import GraphContext
from cjm_graph_domains.domains.structure import Document, Segment
from cjm_graph_domains.domains.relations import StructureRelations

from .models import DecompSegment

# %% ../nbs/graph.ipynb #e22f040d
def build_source_ref(
    seg: DecompSegment,  # Aligned segment carrying upstream provenance
    manifest_path: str,  # Path to the consumed transcription run manifest
) -> Optional[SourceRef]:  # Provenance ref, or None when source info is absent
    """Build a manifest-anchored SourceRef for one segment (CR-19 shape).

    Identity = content_hash over the consumed segment text — verifiable
    regardless of locator resolution, so the E13/D3 dangling-row problem is now
    fixed structurally rather than worked around. Locator = FileRef to the
    consumed run manifest (the file this core actually reads; no more
    `external:<path>` field abuse). slice=None: the consumed region sits inside
    ONE MANIFEST ROW's text, which a slice framed to the manifest FILE cannot
    honestly express (the D4 coordinate-space friction, carried until stage 5
    gives the intra-graph GraphNodeRef(Transcript) + CharSlice anchor). The char
    coordinates and upstream job id stay queryable as Segment node properties.
    """
    if not seg.source_job_id:
        return None
    return SourceRef(
        locator=FileRef(path=manifest_path),
        content_hash=SourceRef.compute_hash(seg.text.encode()),
    )

# %% ../nbs/graph.ipynb #0af0ae04
def build_graph_payload(
    title: str,                     # Document title
    segments: List[DecompSegment],  # Ordered aligned segments (source-coord timing)
    manifest_path: str,             # Consumed manifest path (for SourceRefs)
    media_type: str = "audio",      # Document media type
) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]], str, List[str]]:  # (nodes, edges, doc_id, seg_ids)
    """Build the (nodes, edges, document_id, segment_ids) graph payload.

    Pure: assembles Document + Segment nodes and STARTS_WITH / NEXT / PART_OF
    edges as wire dicts; no capability calls (commit happens in `commit_graph`).
    """
    doc = Document(id=str(uuid4()), title=title, media_type=media_type)
    doc_node = doc.to_graph_node(sources=[])

    segment_nodes = []
    for seg in segments:
        ref = build_source_ref(seg, manifest_path)
        node = Segment(
            id=str(uuid4()), text=seg.text, index=seg.index,
            start_time=seg.start_time, end_time=seg.end_time,
            start_char=seg.start_char, end_char=seg.end_char,
        ).to_graph_node(sources=[ref] if ref else [])
        if seg.source_job_id:
            node.properties["source_job_id"] = seg.source_job_id
        segment_nodes.append(node)

    edges: List[Dict[str, Any]] = []
    if segment_nodes:
        edges.append({"id": str(uuid4()), "source_id": doc_node.id,
                      "target_id": segment_nodes[0].id,
                      "relation_type": StructureRelations.STARTS_WITH, "properties": {}})
    for i, node in enumerate(segment_nodes):
        edges.append({"id": str(uuid4()), "source_id": node.id, "target_id": doc_node.id,
                      "relation_type": StructureRelations.PART_OF, "properties": {}})
        if i < len(segment_nodes) - 1:
            edges.append({"id": str(uuid4()), "source_id": node.id,
                          "target_id": segment_nodes[i + 1].id,
                          "relation_type": StructureRelations.NEXT, "properties": {}})

    nodes = [doc_node.to_dict()] + [n.to_dict() for n in segment_nodes]
    return nodes, edges, doc_node.id, [n.id for n in segment_nodes]

# %% ../nbs/graph.ipynb #199f295a
async def commit_graph(
    queue: JobQueue,              # Started job queue
    graph_id: str,               # Graph-storage capability id
    nodes: List[Dict[str, Any]],  # Node wire dicts from build_graph_payload
    edges: List[Dict[str, Any]],  # Edge wire dicts from build_graph_payload
) -> Dict[str, int]:  # {"nodes": n, "edges": m} created counts
    """Commit nodes then edges to the graph capability via the job queue.

    Goes through `JobQueue` (not a direct `execute_plugin_async`) so graph writes
    get empirical samples + sysmon attribution like every other capability call
    (the GUI GraphService used the direct path — pass-2 two-invocation-paths note).
    """
    async def _run(action, **kw):
        jid = await queue.submit(graph_id, action=action, **kw)
        job = await queue.wait_for_job(jid)
        if job.status != JobStatus.completed:
            raise RuntimeError(f"{graph_id} {action} {job.status}: {job.error}")
        return job.result

    node_res = await _run("add_nodes", nodes=nodes)
    edge_res = await _run("add_edges", edges=edges)
    nc = node_res.get("count", 0) if isinstance(node_res, dict) else 0
    ec = edge_res.get("count", 0) if isinstance(edge_res, dict) else 0
    return {"nodes": nc, "edges": ec}

# %% ../nbs/graph.ipynb #9be74b79
@dataclass
class VerificationResult:
    """Skeptical-lens verification computed by querying the graph directly."""
    document_id: str       # Verified Document node id
    title: str             # Document title (read back from the graph)
    segment_count: int     # Segment nodes found
    has_starts_with: bool  # >=1 STARTS_WITH edge from the Document
    next_chain_complete: bool  # NEXT edge count == segment_count - 1
    part_of_complete: bool     # PART_OF edge count == segment_count
    all_have_timing: bool      # Every segment has start_time + end_time
    all_have_sources: bool     # Every segment has >=1 SourceRef
    source_locators: List[str] = field(default_factory=list)  # Distinct source locator URIs

    @property
    def ok(self) -> bool:  # True when every structural check passes
        """All structural checks pass."""
        return (self.has_starts_with and self.next_chain_complete
                and self.part_of_complete and self.all_have_timing
                and self.all_have_sources)

# %% ../nbs/graph.ipynb #9a42dffb
async def verify_document(
    queue: JobQueue,   # Started job queue
    graph_id: str,     # Graph-storage capability id
    document_id: str,  # Document node id to verify
) -> Optional[VerificationResult]:  # Result, or None if the document is not found
    """Verify a committed document by querying the graph (depth-2 context).

    Skeptical lens: trusts the graph, not the run state — re-reads STARTS_WITH /
    NEXT / PART_OF edges, timing, and source refs from storage. Depth 2 is needed
    so the NEXT edges between discovered Segments are included.
    """
    jid = await queue.submit(graph_id, action="get_context", node_id=document_id, depth=2)
    job = await queue.wait_for_job(jid)
    if job.status != JobStatus.completed:
        raise RuntimeError(f"{graph_id} get_context {job.status}: {job.error}")
    ctx = GraphContext.from_dict(job.result)
    if not ctx.nodes:
        return None

    doc = next((n for n in ctx.nodes if n.label == "Document" and n.id == document_id), None)
    if doc is None:
        return None
    segs = [n for n in ctx.nodes if n.label == "Segment"]
    n = len(segs)

    counts = {"STARTS_WITH": 0, "NEXT": 0, "PART_OF": 0}
    for e in ctx.edges:
        if e.relation_type in counts:
            counts[e.relation_type] += 1

    missing_timing = sum(1 for s in segs
                         if s.properties.get("start_time") is None
                         or s.properties.get("end_time") is None)
    locators = set()
    missing_sources = 0
    for s in segs:
        if not s.sources:
            missing_sources += 1
        for src in s.sources:
            if isinstance(src, dict):
                src = SourceRef.from_dict(src)
            locators.add(src.locator.to_uri())

    return VerificationResult(
        document_id=document_id,
        title=doc.properties.get("title", "Untitled"),
        segment_count=n,
        has_starts_with=counts["STARTS_WITH"] >= 1,
        next_chain_complete=counts["NEXT"] == max(0, n - 1),
        part_of_complete=counts["PART_OF"] == n,
        all_have_timing=missing_timing == 0,
        all_have_sources=missing_sources == 0,
        source_locators=sorted(locators),
    )
